name: Build

on: [workflow_dispatch]

#See latest SDK: https://wiki.teltonika-networks.com/view/Software_Development_Kit
env:
  VERSION: "00.07.04.3"
  CHECKSUM: "2a05900c79e3dacf3d65b2835a855b93"

jobs:
  build:

    runs-on: ubuntu-latest

    timeout-minutes: 210

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          swap-storage: true

      - name: Build
        run: |
          docker build \
            --platform linux/amd64 \
            --pull \
            --build-arg RUTOS_VERSION=$VERSION \
            --build-arg RUTOS_CHECKSUM=$CHECKSUM \
            -t ghcr.io/paresy/rutx-sdk:$VERSION \
            -f Dockerfile .

      - name: Push
        run: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker push ghcr.io/paresy/rutx-sdk:$VERSION